export const SAVE_CAR_WAREHOUSE = 'SAVE_CAR_WAREHOUSE';
export const SAVE_WAREHOUSE_WAREHOUSE = 'SAVE_WAREHOUSE_WAREHOUSE';
export const GET_UNITS_WAREHOUSE = 'GET_UNITS_WAREHOUSE';
export const GET_INVESTMENTS_WAREHOUSE = 'GET_INVESTMENTS_WAREHOUSE';
export const ADD_ITEM_TO_WAREHOUSE_WAREHOUSE = 'ADD_ITEM_TO_WAREHOUSE_WAREHOUSE';
export const CReATE_WAREHOUSE_INVESTMENT_WAREHOUSE = 'CReATE_WAREHOUSE_INVESTMENT_WAREHOUSE';
