export const GET_AGREEMENTS = 'GET_AGREEMENTS';
export const ADD_FOLDER_AGREEMENTS = 'ADD_FOLDER_AGREEMENTS';
export const SET_NAME_FOLDER_AGREEMENTS = 'SET_NAME_FOLDER_AGREEMENTS';
export const DELETE_FOLDER_AGREEMENTS = 'DELETE_FOLDER_AGREEMENTS';
