export const FilePlace = {
    CELL: 'CELL',
    FOLDER: 'FOLDER',
    TABLE_PREV: 'TABLE_PREV',
    TABLE_POST: 'TABLE_POST',
    TABLE_SECOND: 'TABLE_SECOND',
    TABLE_SECOND_POST: 'TABLE_SECOND_POST',
    AGREEMENTS: 'AGREEMENTS',
};
