export const DragTypes = {
    FILES_ABOVE_INVEST: 'FILES_ABOVE_INVEST',
    FOLDER_FILES: 'FOLDER_FILES',
    PREV_FILES_ON_TABLE: 'PREV_FILES_ON_TABLE',
    POST_FILES_ON_TABLE: 'POST_FILES_ON_TABLE',
    SECOND_FILES_ON_TABLE: 'SECOND_FILES_ON_TABLE',
    SECOND_POST_FILES_ON_TABLE: 'SECOND_POST_FILES_ON_TABLE',
};
