export const basicElements = [
    {
        id: -1,
        width: 100,
        height: 100,
        backgroundColor: '#fff',
        radius: 4,
        borderSize: 1,
        borderType: 'solid',
        borderColor: 'yellowgreen',
        fontSize: 16,
        fontWeight: 400,
        color: '#000',
        rotate: 0,
    },
    {
        id: -2,
        width: 100,
        height: 100,
        backgroundColor: '#fff',
        radius: 4,
        borderSize: 1,
        borderType: 'solid',
        borderColor: 'yellowgreen',
        fontSize: 16,
        fontWeight: 400,
        color: '#000',
        rotate: 45,
    },
    {
        id: -3,
        width: 100,
        height: 100,
        backgroundColor: '#fff',
        radius: 50,
        borderSize: 1,
        borderType: 'solid',
        borderColor: 'yellowgreen',
        fontSize: 16,
        fontWeight: 400,
        color: '#000',
        rotate: 0,
    },
    {
        id: -4,
        width: 150,
        height: 80,
        backgroundColor: '#fff',
        radius: '4',
        borderSize: 1,
        borderType: 'solid',
        borderColor: 'yellowgreen',
        fontSize: 16,
        fontWeight: 400,
        color: '#000',
        rotate: 0,
    }
]
