export const ADD_INVESTMENT = 'ADD_TASK';  //done
export const ADD_MIDDLE_STAGE = 'ADD_MIDDLE_STAGE'; //done
export const OPEN_MODAL = 'OPEN_MODAL';  //done
export const CLOSE_MODAL = 'CLOSE_MODAL';  //done
export const CHANGE_STATUS = 'CHANGE_STATUS';  //done
export const UPDATE_MINI_NOTE = 'UPDATE_MINI_NOTE';  //done
export const OPEN_EDIT_CELL = 'OPEN_EDIT_CELL';  //done
export const CLOSE_EDIT_CELL = 'CLOSE_EDIT_CELL';  //done
export const UPDATE_NAME = 'UPDATE_NAME';  //done
export const REMOVE_MIDDLE_TASK = 'REMOVE_MIDDLE_TASK';  //done
export const REMOVE_TASK = 'REMOVE_TASK'; //done
export const ADD_CELL = 'ADD_CELL'; //done
export const ADD_FOLDER = 'ADD_FOLDER'; //done
export const OPEN_FOLDER = 'OPEN_FOLDER'; //done
export const UPDATE_FOLDER_NAME = 'UPDATE_FOLDER_NAME'; //done
export const REMOVE_FOLDER = 'REMOVE_FOLDER'; //done
export const REMOVE_DOCUMENT = 'REMOVE_DOCUMENT_FROM_CELL'; //done
export const ADD_INVEST_FILE = 'ADD_INVEST_FILE'; //done
export const ADD_FILE_TO_FOLDER = 'ADD_FILE_TO_FOLDER'; //done
export const UPDATE_NOTE = 'UPDATE_NOTE'; // done
export const UPDATE_ADDITIONAL_CELL = 'UPDATE_ADDITIONAL_CELL'; //done
export const ADD_TABLE = 'ADD_TABLE';  //done
export const SET_TITLE_TABLE = 'SET_TITLE_TABLE'; //done
export const SET_FIRST_COLUMN = 'SET_FIRST_COLUMN'; //done
export const SET_MAIN_CELLS_NAME = 'SET_MAIN_CELLS_NAME'; //done
export const UPLOAD_FILE_TO_TABLE = 'UPLOAD_FILE_TO_TABLE'; //done
export const SET_DATE_IN_TABLE = 'SET_DATE_IN_TABLE'; //done
export const SELECT_STATUS_IN_TABLE = 'SELECT_STATUS_IN_TABLE'; //done
export const DELETE_TABLE = 'DELETE_TABLE'; //done
export const ALL_FILES_UPLOADED = 'ALL_FILES_UPDATED'; //done
export const DELETE_TABLE_ROW = 'DELETE_ROW'; //done
export const ADD_TABLE_ROW = 'ADD_TABLE_ROW'; //done
export const ADD_COLUMN = 'ADD_COLUMN';
export const IS_LOADING = 'IS_LOADING';
export const IS_ERROR = 'IS_ERROR';
export const IS_SUCCESS = 'IS_SUCCESS';
export const RESET_ERROR_SUCCESS = 'RESET_ERROR_SUCCESS';
export const FIND_OBJECTS_IDS = 'FIND_OBJECT';
export const GET_DATA = 'GET_DATA';
export const GET_POSITIONS = 'GET_POSITIONS';
export const UPDATE_MAIN_INVEST = 'UPDATE_MAIN_INVEST';
export const SET_PERMISSIONS = 'SET_PERMISSIONS';
export const SET_DRAWER = 'SET_DRAWER';
export const UPDATE_INVESTMENT_ID = 'UPDATE_INVESTMENT_ID';
export const UPDATE_ORDER_TASK_INVESTMENT = 'UPDATE_ORDER_TASK_INVESTMENT';
export const FETCH_DRAWERS = 'FETCH_DRAWERS';
export const SAVE_DRAWER_INVESTMENT = 'SAVE_DRAWER_INVESTMENT';
export const UPDATE_DRAWER_INVESTMENT = 'UPDATE_DRAWER_INVESTMENT';
export const DELETE_DRAWER_INVESTMENT = 'DELETE_DRAWER_INVESTMENT';

