export const Graph = {
    FETCH: 'FETCHGRAPH',
    ADD_ELEMENT: 'GRAPHADDELEMENT',
    FETCH_TEMPLATE: 'GRAPH_FETCH_TEMPLATE',
    FETCH_EDGES: 'GRAPH_FETCH_EDGES',
    CHANGE_HANDLE: 'GRAPH_CHANGE_HANDLE',
    ADD_HANDLE: 'GRAPH_ADD_HANDLE',
    FETCH_GRAPH_PERMISSIONS: 'GRAPH_FETCH_GRAPH_PERMISSIONS',
}
